### ISSUE TITLE
any timeline for code/model weights?

### ISSUE THREAD

**Issue by xnmt9** [showlab/MotionDirector#1]
hello 👋🏽 incredible work you guys are doing. excited to play with it, just wondering when you're thinking of releasing code?

**Comment by ruizhaocv** [comment]
Thanks for your interest. We will release the code in around one month. Please stay tuned!

**Comment by Kyfafyd** [comment]
Any update on this? 👀

**Comment by ninjasaid2k** [comment]
I hope it's released!

**Comment by Bailey-24** [comment]
very hungry

**Comment by TruthSearcher** [comment]
is there any update from showlab?

**Comment by akk-123** [comment]
@ruizhaocv when will release code？

**Comment by ruizhaocv** [comment]
Hi all. Thanks for your interest. The code and weights have been released.
