### ISSUE TITLE
The code for directly finetune the foundation model

### ISSUE THREAD

**Issue by bin123apple** [showlab/MotionDirector#14]
Hey,  thanks for your great work! And I hope your paper can be accepted by ICLR. I am a new guy in this area, and still trying to learn the diffusion model. I wonder if you have the code for directly finetuning the foundation model instead of customizing it? I am trying to use different motions instead of one to directly finetune it... if not, can it be achieved by modifying some code instead your _MotionDirector_train.py_ file? Thanks a lot for any help!

**Comment by ruizhaocv** [comment]
Hi. Thanks! Our code can be adapted to directly fine-tuning the foundation model. But I think it is more straightforward for you to use this awesome repo: https://github.com/ExponentialML/Text-To-Video-Finetuning.

**Comment by bin123apple** [comment]
Thanks！
