### ISSUE TITLE
Errors in dataset.py

### ISSUE THREAD

**Issue by XiaominLi1997** [showlab/MotionDirector#15]
hi, I have checked vr[0].shape, that is, (h, w, c).
![image](https://github.com/showlab/MotionDirector/assets/25433111/cbd96e14-9c32-43f6-8a6b-7bb2d7c9823e)
 I have no idea if this problem is caused by the version of decord? I use decord==0.6.0 as requirements.txt

**Comment by ruizhaocv** [comment]
Hi, Xiaomin. This is an old bug in the base code, but it didn't influence the training process. I have fixed this issue in the updated version. Thanks for pointing this out.

**Comment by XiaominLi1997** [comment]
I found it, thx.
