### ISSUE TITLE
Some confusion about the inconsistency between code and paper description

### ISSUE THREAD

**Issue by LiuHuijie6410** [showlab/MotionDirector#29]
I appreciate your awesome work very much. However, there are some things I don't understand.
During the training process, each iteration has a 20% probability that mask_spatial_lora is True, and mask_temporal_lora is always False.  If a certain lora is masked, the lora scale of this part will be set to 0. This does not freeze the lora, but cancels the lora. This is inconsistent with the dual channel mentioned in the paper. Is it because I didn’t understand the code?
thank you for your reply

**Comment by ruizhaocv** [comment]
Hi. This trick is just for faster training. You can simply set the probability to 0%.

**Comment by LiuHuijie6410** [comment]
> Hi. This trick is just for faster training. You can simply set the probability to 0%.

Sorry, maybe I didn't make it clear what I meant. I mean when training, if you want to freeze spatial lora, you set lora_i = 0. But I think this operation only bypasses lora, rather than freezing lora.

**Comment by LiuHuijie6410** [comment]
> Hi. This trick is just for faster training. You can simply set the probability to 0%.

Maybe I misunderstood the meaning of mask_temporal_lora and mask_spatial_lora. Could you please introduce these two variables?

**Comment by ruizhaocv** [comment]
In the forward process, setting lora_i = 0 makes sure the corresponding LoRA will not influence the outputs and the loss calculation. In the backward process, the corresponding optimizer will not update and parameters of the LoRA is frozen.
