### ISSUE TITLE
How to use MotionDirector to train a LoRA based on other base models?

### ISSUE THREAD

**Issue by LiuHuijie6410** [showlab/MotionDirector#43]
Thanks for such amazing work！
I want to use MotionDirector to train LoRa based on **Stable Video Diffusion** or **ModelScope_v1.5**.
Is this easy to implement? Do I need to rewrite the code in utils to insert lora? 
ps. The ModelScope_v1.5 I mentioned is https://modelscope.cn/models/iic/dreamvideo-t2v/summary.
Thanks for your reply!

**Comment by ruizhaocv** [comment]
Yes, you need to rewrite to adapt to their code base.
