### ISSUE TITLE
Weird Results

### ISSUE THREAD

**Issue by xizaoqu** [showlab/MotionDirector#9]
Hi~ Thanks for sharing your inspiring work. But why is my output not as expected?

![A_tank_is_running_on_the_moon_8551187](https://github.com/showlab/MotionDirector/assets/45515569/408d6be5-231f-405b-b4cb-db1d894038f4)

Below is my config
{
            "name": "Python: inference",
            "type": "python",
            "request": "launch",
            "program": "MotionDirector_inference.py",
            "console": "integratedTerminal",
            "justMyCode": false,
            "args": ["--model", "/mnt/lustre/usr/.cache/huggingface/hub/models--cerspense--zeroscope_v2_576w/snapshots/6963642a64dbefa93663d1ecebb4ceda2d9ecb28",
                    "--prompt", "A tank is running on the moon.",
                    "--checkpoint_folder", "/mnt/lustre/usr/outputs/train/car_16",
                    "--checkpoint_index", "150", 
                    "--noise_prior", "0.5",
                    "--seed", "8551187"]
 }

**Comment by ruizhaocv** [comment]
Using the same seed in a different environment may result in the generation of a different initial noise. You can try using a different random seed and see the effect.

**Comment by xizaoqu** [comment]
Thanks for your quick reply. I tried another seed and the problem remains (following prompt but not motion lora).
![A_tank_is_running_on_the_moon_12345](https://github.com/showlab/MotionDirector/assets/45515569/13883c06-c66e-4228-8752-7770ddf612e8)

**Comment by YRlin-12** [comment]
Same Problem.
Anyone solved?

**Comment by ruizhaocv** [comment]
Hi. You can try the new checkpoint:
`git clone https://huggingface.co/ruizhaocv/MotionDirector_weights.git ./outputs
`
And run the command:
`python MotionDirector_inference.py --model /path/to/the/ZeroScope  --prompt "A tank is running on the moon." --checkpoint_folder ./outputs/train/car_16/ --checkpoint_index 200 --noise_prior 0.5 --seed 2424022
`
Then check out the results.

**Comment by xizaoqu** [comment]
Thanks for the update! Now the results are much better.
![A_tank_is_running_on_the_moon_12345](https://github.com/showlab/MotionDirector/assets/45515569/bc91b58f-8181-4eb4-8faa-1e9d75d4ed84)
